defaults:
  - _self_
  - datapaths: datapaths

development_mode: false

CDS_API_KEY: 
  path: "$HOME/.cdsapirc"

query: 
  product_type: reanalysis
  gadm_file: "https://geodata.ucdavis.edu/gadm/gadm4.1/gpkg/gadm41_MDG.gpkg"
  # check precipitation
  # variable: ["2m_dewpoint_temperature", "2m_temperature", "skin_temperature", "total_precipitation"]
  variable: ["2m_dewpoint_temperature", "2m_temperature"]
  year: [2010, 2011]
  month: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  day: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
  time: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
  
  # this may have to be added for the 
  #levtype: pl
  # in the current workflow we can test with a small number of healthsheds
  # this bounding box will need to be expanded by ~ 50km (in G's dataset it is 50) or even up to 70 or 08
  # we can also experiment with a buffer that follows the coastline precisely by 100KM

  area: [0, 360, -90, 90]
  data_format: netcdf
  download_format: unarchived

# logging config
hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}